var dir_68267d1309a1af8e8297ef4c3efbcdba =
[
    [ "cbessel.f90", "cbessel_8f90_source.html", null ],
    [ "ddx.f90", "ddx_8f90_source.html", null ],
    [ "ddx.h", "ddx_8h.html", "ddx_8h" ],
    [ "ddx_cinterface.f90", "ddx__cinterface_8f90_source.html", null ],
    [ "ddx_constants.f90", "ddx__constants_8f90.html", "ddx__constants_8f90" ],
    [ "ddx_core.f90", "ddx__core_8f90.html", "ddx__core_8f90" ],
    [ "ddx_cosmo.f90", "ddx__cosmo_8f90.html", "ddx__cosmo_8f90" ],
    [ "ddx_definitions.f90", "ddx__definitions_8f90.html", "ddx__definitions_8f90" ],
    [ "ddx_driver.f90", "ddx__driver_8f90.html", "ddx__driver_8f90" ],
    [ "ddx_errors.f90", "ddx__errors_8f90_source.html", null ],
    [ "ddx_gradients.f90", "ddx__gradients_8f90_source.html", null ],
    [ "ddx_harmonics.f90", "ddx__harmonics_8f90.html", "ddx__harmonics_8f90" ],
    [ "ddx_legacy.f90", "ddx__legacy_8f90_source.html", null ],
    [ "ddx_lpb.f90", "ddx__lpb_8f90_source.html", null ],
    [ "ddx_lpb_core.f90", "ddx__lpb__core_8f90_source.html", null ],
    [ "ddx_multipolar_solutes.f90", "ddx__multipolar__solutes_8f90_source.html", null ],
    [ "ddx_operators.f90", "ddx__operators_8f90.html", "ddx__operators_8f90" ],
    [ "ddx_parameters.f90", "ddx__parameters_8f90.html", "ddx__parameters_8f90" ],
    [ "ddx_pcm.f90", "ddx__pcm_8f90.html", "ddx__pcm_8f90" ],
    [ "ddx_solvers.f90", "ddx__solvers_8f90.html", "ddx__solvers_8f90" ],
    [ "ddx_workspace.f90", "ddx__workspace_8f90.html", "ddx__workspace_8f90" ],
    [ "llgnew.f", "llgnew_8f_source.html", null ]
];