name: Publish package
on:
  push:
    branches: [master]
    tags: ['v*']
  workflow_dispatch:

jobs:
  publish_pypi:
    name: Publish 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libblas-dev liblapack-dev
          python -m pip install --user wheel pybind11 pytest
          python -m pip install --user -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest src
      - name: Build a source tarball
        run: python setup.py sdist
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

